version: '3.8'
services:
  app:
    container_name: backend-app
    build:
      context: .
    image: backend-dev
    environment:
      - NODE_ENV=dev
    command:
      - tail
      - -f
    volumes:
      - .:/app
volumes:
  npm-cache:
